app = "listenary-db-aaaaabiang"
primary_region = "arn"

[build]
  image = "mongo:latest"

[mounts]
  source = "mongo_data"
  destination = "/data/db"

[[services]]
  internal_port = 27017
  protocol = "tcp"
  processes = ["app"]
  
  [[services.ports]]
    port = 27017

[processes]
  app = "mongod --bind_ip_all --port 27017"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1